export const QUERY_KEY = {
  USERS: {
    GET_CURRENT_USER: 'USERS/GET_CURRENT_USER',
  },
  CATEGORIES: {
    GET_CATEGORIES: 'CATEGORIES/GET_CATEGORIES',
    GET_CATEGORY: 'CATEGORIES/GET_CATEGORY',
    GET_CATEGORY_AND_CATEGORY_PRODUCTS:
      'CATEGORIES/GET_CATEGORY_AND_CATEGORY_PRODUCTS',
  },
  VOUCHERS: {
    GET_VOUCHERS: 'VOUCHERS/GET_VOUCHERS',
    GET_VOUCHER: 'VOUCHERS/GET_VOUCHER',
  },
  PRODUCTS: {
    GET_PRODUCTS: 'PRODUCTS/GET_PRODUCTS',
    GET_PRODUCT: 'PRODUCTS/GET_PRODUCT',
    GET_PRODUCTS_BY_CATEGORY_AND_NAME:
      'PRODUCTS/GET_PRODUCTS_BY_CATEGORY_AND_NAME',
    GET_PRODUCTS_BY_LIST_IDS: 'PRODUCTS/GET_PRODUCTS_BY_LIST_IDS',
  },
  ORDERS: {
    GET_ORDERS: 'ORDERS/GET_ORDERS',
    GET_ORDER: 'ORDERS/GET_ORDER',
    GET_ORDER_ITEMS: 'ORDERS/GET_ORDER_ITEMS',
  },
};
